### ISSUE TITLE
add <itunes:email> to feed

### ISSUE THREAD

**Issue by samuelheer** [lukasbableck/contao-podcast-feed-bundle#2]
Hi, 
I wanted to submit the generated feed to Spotify, but get an error. Email is not set.
Could you please add a field for that in the page settings?
In the xml it should go in <itunes:email>

Thanks a lot in advance!

<img width="607" alt="Bildschirmfoto 2024-09-05 um 15 45 49" src="https://github.com/user-attachments/assets/48d1fb90-3520-4081-afbe-936c2f45042e">

**Comment by lukasbableck** [comment]
Done and released in 1.2.0.
Please check if this resolves the issue with Spotify.

**Comment by samuelheer** [comment]
perfect! thanks a lot! 🎉
