### ISSUE TITLE
podcastSummery needs default value

### ISSUE THREAD

**Issue by samuelheer** [lukasbableck/contao-podcast-feed-bundle#3]
**Describe the bug**
In some environments 'text' fields needs default value set, otherwise you get an error when creating a new news. 

![Unknown](https://github.com/user-attachments/assets/f80b9274-c3b5-40b4-9878-94a3944d1d4a)

Please add 'default' => '', to the podcastSummary field definition.

**Comment by lukasbableck** [comment]
I'm not able to reproduce this, can you add more information to the database version and Contao version?
Contao 5.3 and 5.4 with MariaDB 10.11.6 does not seem to have that problem.

I have changed the column definition to text NULL in dev-main, can you check if this also fixes the issue?

**Comment by samuelheer** [comment]
The environment which produced the error was: MySQL 8.0/ InnoDB / utf8mb4_unicode, Contao 5.3.13.

Your change fixed the problem. 👍

**Comment by lukasbableck** [comment]
Ok, probably specific to MySQL then. I have released the fix as 1.2.1.
